services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
      POSTGRES_MULTIPLE_DATABASES: local,test
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker-init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh

volumes:
  db-data:
    driver: local


